import { css } from "@emotion/react";
export const styles = css`
  position: absolute;
  left: 196px;
  top: 6px;
  @keyframes ldio-m9rglga6xpj {
    0% {
      transform: translate(-50%, -50%) rotate(0deg);
    }
    100% {
      transform: translate(-50%, -50%) rotate(360deg);
    }
  }
  .ldio-m9rglga6xpj div {
    position: absolute;
    width: 50px;
    height: 50px;
    border: 5px solid #ffffff;
    border-top-color: transparent;
    border-radius: 50%;
  }
  .ldio-m9rglga6xpj div {
    animation: ldio-m9rglga6xpj 1.1363636363636365s linear infinite;
    top: 50px;
    left: 50px;
  }
  .loadingio-spinner-rolling-fjdbmh4f8o {
    width: 37px;
    height: 37px;
    display: inline-block;
    overflow: hidden;
    background: #dddddd;
  }
  .ldio-m9rglga6xpj {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(0.37);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-m9rglga6xpj div {
    box-sizing: content-box;
  }
  /* generated by https://loading.io/ */
`;
