import { css } from "@emotion/react";
export const styles = css`
  position: absolute;
  left: 43%;
  top: 30%;

  @keyframes ldio-sr9ndies19k {
    0% {
      opacity: 1;
    }
    100% {
      opacity: 0;
    }
  }
  .ldio-sr9ndies19k div {
    left: 144.48px;
    top: 72.24px;
    position: absolute;
    animation: ldio-sr9ndies19k linear 0.9090909090909091s infinite;
    background: #57b3e4;
    width: 12.04px;
    height: 42.14px;
    border-radius: 6.02px / 21.07px;
    transform-origin: 6.02px 78.25999999999999px;
  }
  .ldio-sr9ndies19k div:nth-child(1) {
    transform: rotate(0deg);
    animation-delay: -0.8522727272727272s;
    background: #57b3e4;
  }
  .ldio-sr9ndies19k div:nth-child(2) {
    transform: rotate(22.5deg);
    animation-delay: -0.7954545454545454s;
    background: #57b3e4;
  }
  .ldio-sr9ndies19k div:nth-child(3) {
    transform: rotate(45deg);
    animation-delay: -0.7386363636363635s;
    background: #57b3e4;
  }
  .ldio-sr9ndies19k div:nth-child(4) {
    transform: rotate(67.5deg);
    animation-delay: -0.6818181818181818s;
    background: #57b3e4;
  }
  .ldio-sr9ndies19k div:nth-child(5) {
    transform: rotate(90deg);
    animation-delay: -0.625s;
    background: #57b3e4;
  }
  .ldio-sr9ndies19k div:nth-child(6) {
    transform: rotate(112.5deg);
    animation-delay: -0.5681818181818181s;
    background: #57b3e4;
  }
  .ldio-sr9ndies19k div:nth-child(7) {
    transform: rotate(135deg);
    animation-delay: -0.5113636363636364s;
    background: #57b3e4;
  }
  .ldio-sr9ndies19k div:nth-child(8) {
    transform: rotate(157.5deg);
    animation-delay: -0.45454545454545453s;
    background: #57b3e4;
  }
  .ldio-sr9ndies19k div:nth-child(9) {
    transform: rotate(180deg);
    animation-delay: -0.3977272727272727s;
    background: #57b3e4;
  }
  .ldio-sr9ndies19k div:nth-child(10) {
    transform: rotate(202.5deg);
    animation-delay: -0.3409090909090909s;
    background: #57b3e4;
  }
  .ldio-sr9ndies19k div:nth-child(11) {
    transform: rotate(225deg);
    animation-delay: -0.28409090909090906s;
    background: #57b3e4;
  }
  .ldio-sr9ndies19k div:nth-child(12) {
    transform: rotate(247.5deg);
    animation-delay: -0.22727272727272727s;
    background: #57b3e4;
  }
  .ldio-sr9ndies19k div:nth-child(13) {
    transform: rotate(270deg);
    animation-delay: -0.17045454545454544s;
    background: #57b3e4;
  }
  .ldio-sr9ndies19k div:nth-child(14) {
    transform: rotate(292.5deg);
    animation-delay: -0.11363636363636363s;
    background: #57b3e4;
  }
  .ldio-sr9ndies19k div:nth-child(15) {
    transform: rotate(315deg);
    animation-delay: -0.056818181818181816s;
    background: #57b3e4;
  }
  .ldio-sr9ndies19k div:nth-child(16) {
    transform: rotate(337.5deg);
    animation-delay: 0s;
    background: #57b3e4;
  }
  .loadingio-spinner-spinner-3bo3f4s24dt {
    width: 301px;
    height: 301px;
    display: inline-block;
    overflow: hidden;
    background: #f1f2f3;
  }
  .ldio-sr9ndies19k {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-sr9ndies19k div {
    box-sizing: content-box;
  }
  /* generated by https://loading.io/ */
`;
